### ISSUE TITLE
leblad API documentation: checklist

### ISSUE THREAD

**Issue by omdxp** [omdxp/leblad-rs#34]
**Description**
This milestone is dedicated to implement leblad API for Rust.

**Check List**
- [x] #35
- [x] `get_wilaya_by_zip_code` function docs
- [x] `get_wilaya_by_code` function docs
- [x] `get_adjacent_wilayas` function docs
- [x] `get_zip_codes_for_wilaya` function docs
- [x] `get_dairats_for_wilaya` function docs
- [x] `get_wilaya_by_phone_code` function docs
- [x] `get_wilaya_by_daira_name` function docs
- [x] `get_baladyiats_for_daira` function docs
- [x] `get_baladyiats_for_daira_code` function docs
- [x] `get_phone_codes_for_wilaya` function docs
- [x] `get_first_phone_code_for_wilaya` function docs
- [x] `get_baladyiats_for_wilaya` function docs
- [x] `get_wilaya_by_baladyia_name` function docs
- [x] `get_daira_by_baladyia_name` function docs
- [x] #37
